/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedSharedIndexRouteImport } from './routes/_authenticated/shared/index'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedRecentIndexRouteImport } from './routes/_authenticated/recent/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedFavoritesIndexRouteImport } from './routes/_authenticated/favorites/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthFeaturesIndexRouteImport } from './routes/_auth/features/index'
import { Route as AuthActivateIndexRouteImport } from './routes/_auth/activate/index'
import { Route as AuthAboutIndexRouteImport } from './routes/_auth/about/index'
import { Route as AuthenticatedFolderFolderIdRouteImport } from './routes/_authenticated/folder/$folderId'
import { Route as AuthenticatedDashboardViewIndexRouteImport } from './routes/_authenticated/dashboard/view/index'
import { Route as AuthenticatedDocumentsDocidViewIndexRouteImport } from './routes/_authenticated/documents/$docid/view/index'
import { Route as AuthenticatedDocumentsDocidEditIndexRouteImport } from './routes/_authenticated/documents/$docid/edit/index'
import { Route as AuthenticatedDocumentsDocidCreateIndexRouteImport } from './routes/_authenticated/documents/$docid/create/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharedIndexRoute =
  AuthenticatedSharedIndexRouteImport.update({
    id: '/shared/',
    path: '/shared/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecentIndexRoute =
  AuthenticatedRecentIndexRouteImport.update({
    id: '/recent/',
    path: '/recent/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFavoritesIndexRoute =
  AuthenticatedFavoritesIndexRouteImport.update({
    id: '/favorites/',
    path: '/favorites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFeaturesIndexRoute = AuthFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthActivateIndexRoute = AuthActivateIndexRouteImport.update({
  id: '/activate/',
  path: '/activate/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAboutIndexRoute = AuthAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedFolderFolderIdRoute =
  AuthenticatedFolderFolderIdRouteImport.update({
    id: '/folder/$folderId',
    path: '/folder/$folderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardViewIndexRoute =
  AuthenticatedDashboardViewIndexRouteImport.update({
    id: '/dashboard/view/',
    path: '/dashboard/view/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocidViewIndexRoute =
  AuthenticatedDocumentsDocidViewIndexRouteImport.update({
    id: '/documents/$docid/view/',
    path: '/documents/$docid/view/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocidEditIndexRoute =
  AuthenticatedDocumentsDocidEditIndexRouteImport.update({
    id: '/documents/$docid/edit/',
    path: '/documents/$docid/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocidCreateIndexRoute =
  AuthenticatedDocumentsDocidCreateIndexRouteImport.update({
    id: '/documents/$docid/create/',
    path: '/documents/$docid/create/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/folder/$folderId': typeof AuthenticatedFolderFolderIdRoute
  '/about': typeof AuthAboutIndexRoute
  '/activate': typeof AuthActivateIndexRoute
  '/features': typeof AuthFeaturesIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/favorites': typeof AuthenticatedFavoritesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/recent': typeof AuthenticatedRecentIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/shared': typeof AuthenticatedSharedIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/dashboard/view': typeof AuthenticatedDashboardViewIndexRoute
  '/documents/$docid/create': typeof AuthenticatedDocumentsDocidCreateIndexRoute
  '/documents/$docid/edit': typeof AuthenticatedDocumentsDocidEditIndexRoute
  '/documents/$docid/view': typeof AuthenticatedDocumentsDocidViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/folder/$folderId': typeof AuthenticatedFolderFolderIdRoute
  '/about': typeof AuthAboutIndexRoute
  '/activate': typeof AuthActivateIndexRoute
  '/features': typeof AuthFeaturesIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/favorites': typeof AuthenticatedFavoritesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/recent': typeof AuthenticatedRecentIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/shared': typeof AuthenticatedSharedIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/dashboard/view': typeof AuthenticatedDashboardViewIndexRoute
  '/documents/$docid/create': typeof AuthenticatedDocumentsDocidCreateIndexRoute
  '/documents/$docid/edit': typeof AuthenticatedDocumentsDocidEditIndexRoute
  '/documents/$docid/view': typeof AuthenticatedDocumentsDocidViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_authenticated/folder/$folderId': typeof AuthenticatedFolderFolderIdRoute
  '/_auth/about/': typeof AuthAboutIndexRoute
  '/_auth/activate/': typeof AuthActivateIndexRoute
  '/_auth/features/': typeof AuthFeaturesIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/favorites/': typeof AuthenticatedFavoritesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/recent/': typeof AuthenticatedRecentIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/shared/': typeof AuthenticatedSharedIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/dashboard/view/': typeof AuthenticatedDashboardViewIndexRoute
  '/_authenticated/documents/$docid/create/': typeof AuthenticatedDocumentsDocidCreateIndexRoute
  '/_authenticated/documents/$docid/edit/': typeof AuthenticatedDocumentsDocidEditIndexRoute
  '/_authenticated/documents/$docid/view/': typeof AuthenticatedDocumentsDocidViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/folder/$folderId'
    | '/about'
    | '/activate'
    | '/features'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/recent'
    | '/search'
    | '/shared'
    | '/tags'
    | '/dashboard/view'
    | '/documents/$docid/create'
    | '/documents/$docid/edit'
    | '/documents/$docid/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/folder/$folderId'
    | '/about'
    | '/activate'
    | '/features'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/recent'
    | '/search'
    | '/shared'
    | '/tags'
    | '/dashboard/view'
    | '/documents/$docid/create'
    | '/documents/$docid/edit'
    | '/documents/$docid/view'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/'
    | '/_authenticated/folder/$folderId'
    | '/_auth/about/'
    | '/_auth/activate/'
    | '/_auth/features/'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/favorites/'
    | '/_authenticated/profile/'
    | '/_authenticated/recent/'
    | '/_authenticated/search/'
    | '/_authenticated/shared/'
    | '/_authenticated/tags/'
    | '/_authenticated/dashboard/view/'
    | '/_authenticated/documents/$docid/create/'
    | '/_authenticated/documents/$docid/edit/'
    | '/_authenticated/documents/$docid/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared/': {
      id: '/_authenticated/shared/'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof AuthenticatedSharedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recent/': {
      id: '/_authenticated/recent/'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AuthenticatedRecentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites/': {
      id: '/_authenticated/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/features/': {
      id: '/_auth/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthFeaturesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/activate/': {
      id: '/_auth/activate/'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthActivateIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/about/': {
      id: '/_auth/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/folder/$folderId': {
      id: '/_authenticated/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof AuthenticatedFolderFolderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/view/': {
      id: '/_authenticated/dashboard/view/'
      path: '/dashboard/view'
      fullPath: '/dashboard/view'
      preLoaderRoute: typeof AuthenticatedDashboardViewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$docid/view/': {
      id: '/_authenticated/documents/$docid/view/'
      path: '/documents/$docid/view'
      fullPath: '/documents/$docid/view'
      preLoaderRoute: typeof AuthenticatedDocumentsDocidViewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$docid/edit/': {
      id: '/_authenticated/documents/$docid/edit/'
      path: '/documents/$docid/edit'
      fullPath: '/documents/$docid/edit'
      preLoaderRoute: typeof AuthenticatedDocumentsDocidEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$docid/create/': {
      id: '/_authenticated/documents/$docid/create/'
      path: '/documents/$docid/create'
      fullPath: '/documents/$docid/create'
      preLoaderRoute: typeof AuthenticatedDocumentsDocidCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAboutIndexRoute: typeof AuthAboutIndexRoute
  AuthActivateIndexRoute: typeof AuthActivateIndexRoute
  AuthFeaturesIndexRoute: typeof AuthFeaturesIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAboutIndexRoute: AuthAboutIndexRoute,
  AuthActivateIndexRoute: AuthActivateIndexRoute,
  AuthFeaturesIndexRoute: AuthFeaturesIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFolderFolderIdRoute: typeof AuthenticatedFolderFolderIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedFavoritesIndexRoute: typeof AuthenticatedFavoritesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedRecentIndexRoute: typeof AuthenticatedRecentIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedSharedIndexRoute: typeof AuthenticatedSharedIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedDashboardViewIndexRoute: typeof AuthenticatedDashboardViewIndexRoute
  AuthenticatedDocumentsDocidCreateIndexRoute: typeof AuthenticatedDocumentsDocidCreateIndexRoute
  AuthenticatedDocumentsDocidEditIndexRoute: typeof AuthenticatedDocumentsDocidEditIndexRoute
  AuthenticatedDocumentsDocidViewIndexRoute: typeof AuthenticatedDocumentsDocidViewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFolderFolderIdRoute: AuthenticatedFolderFolderIdRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedFavoritesIndexRoute: AuthenticatedFavoritesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedRecentIndexRoute: AuthenticatedRecentIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedSharedIndexRoute: AuthenticatedSharedIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedDashboardViewIndexRoute: AuthenticatedDashboardViewIndexRoute,
  AuthenticatedDocumentsDocidCreateIndexRoute:
    AuthenticatedDocumentsDocidCreateIndexRoute,
  AuthenticatedDocumentsDocidEditIndexRoute:
    AuthenticatedDocumentsDocidEditIndexRoute,
  AuthenticatedDocumentsDocidViewIndexRoute:
    AuthenticatedDocumentsDocidViewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
